sudo: false
dist: trusty

language: node_js
node_js: '12'

# Since Travis is running on the Ubuntu 16+
# this library is necessary
# see https://github.com/cypress-io/cypress/issues/4069#issuecomment-488816887
addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - yarn --pure-lockfile --non-interactive

script:
  - yarn select-snapshot-ivy:lint
  - yarn select-snapshot-ivy:build

  # Currently unit tests are running using view engine
  # fix it laster
  # - yarn test:ci
  # - yarn test:ci:integration
  # - yarn test:ci:integration:ssr

  # But still we can test it using E2E tests
  - yarn build:integration
  - yarn test:ci:e2e
